spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/happyhour
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:mysecretpassword}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
        jdbc:
          time_zone: UTC
        show_sql: true
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:auto}
  flyway:
    baseline-on-migrate: true
  codec:
    log-request-details: true


# Log HTTP requests and responses
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.http: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

server:
  error:
    include-message: always

happyhour:
  openai:
    url: https://ue7nks7sl1.execute-api.us-east-1.amazonaws.com/prod/openai
  yelp:
    token: XDwCmuL1K5vxxPKjtnvKM4hujDC1nQPO1i2QR3HpPC5ImddyfAqQvWCpQZpDfVSzwFrM5L1Fy5RlQJqXJvcfZRZRbEEsGc__XlSvfTQPfKtoWchtGsUWQmcRiJzJZHYx
